[package]
name = "nfshdr"
version = "0.1.0"
authors = ["Trip Volpe <trip.volpe@gmail.com>"]

[dependencies]
docopt = "0.8"
pcap = "*"
pnet_packet = "*"
serde = "1.0"
serde_derive = "1.0"

[features]
default = []
slow = []
